# ç½‘ç«™ä¿¡æ¯
site:
  name:
    class: text
    custom: LUOH-AN # Solitude / fas fa-ghost / /img/pwa/favicon.ico
  icon: /img/favicon.ico

# å¯¼èˆªæ 
nav:
  # å·¦ä¾§ç›’å­
  group:
    æˆ‘çš„:
      éŸ³ä¹é¦†: https://music.luoh.pages.dev/ || https://fastly.jsdelivr.net/gh/Richard9394/MingCute@master/svg/media/music_3_fill.svg
      MIKUTAP: https://mikutap.luoh.pages.dev/ || https://fastly.jsdelivr.net/gh/Richard9394/MingCute@master/svg/media/music_2_ai_fill.svg
      è¡¨æƒ…ä¸€è§ˆ: https://emoji-show.luoh.pages.dev/ || https://fastly.jsdelivr.net/gh/Richard9394/MingCute@master/svg/emoji/emoji_fill.svg
      Cover: https://pic.chino.my.to/cover || https://fastly.jsdelivr.net/gh/Richard9394/MingCute@master/svg/design/background_fill.svg

  # èœå•
  menu:
    # é¦–é¡µ: / # name: link
    æ–‡åº“: # name
      å…¨éƒ¨æ–‡ç« : /archives/ || fas fa-folder-closed # item name: link || icon
      åˆ†ç±»åˆ—è¡¨: /categories/ || fas fa-clone
      æ ‡ç­¾åˆ—è¡¨: /tags/ || fas fa-tags
    å‹é“¾:
      å‹æƒ…é“¾æ¥: /links/ || fas fa-user-group
      å®è—åšä¸»: javascript:travelling() || fas fa-gift
    æˆ‘çš„:
      æˆ‘çš„è£…å¤‡: /equipment/ || fas fa-tools
      # åœ¨çº¿å·¥å…·: /tlink/ || fas fa-toolbox
      å…³äºæœ¬ç«™: /about/ || fas fa-user

  # å³ä¾§æŒ‰é’®
  right:
    random: true # Random article / éšæœºæ–‡ç« æŒ‰é’®
    custom:
    #  - name: å¼€å¾€ # åå­—
    #    url: https://www.travellings.cn/go.html # è·³è½¬é“¾æ¥
    #    icon: fas fa-train # å›¾æ ‡
    #    onclick: # ç‚¹å‡»äº‹ä»¶
    #    id: travellings_button # id

# é¦–é¡µé¡¶éƒ¨
hometop:
  enable: true
  banner:
    title: ç™½å‘ç™½è¡£çš†å‚åœ°<br> èŠ±å¼€èŠ±è°¢å¤å››å­£
    url: è½äººé—´ï¼Œæ¸éšå¼¦ï¼Œç¦»æ„å®£ã€‚
    icon:
      Nodejs:
        img: https://ui.everfu.cn/cover/20240827172946.png/cover
        color: "#242938"
      Vue:
        img: https://ui.everfu.cn/cover/20240827173146.png/cover
        color: "#242938"
      React:
        img: https://ui.everfu.cn/avatar/20240827172839.png/cover
        color: "#242938"
      HTML:
        img: https://ui.everfu.cn/cover/20240827173208.png/cover
        color: "#e34c26"
      CSS:
        img: https://ui.everfu.cn/cover/20240827173227.png/cover
        color: "#0277BD"
      JavaScript:
        img: https://ui.everfu.cn/cover/20240827173248.png/cover
        color: "#EFDB50"
  group:
    çƒ­é—¨: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    sup: ç½®é¡¶
    title: Solitude å®˜æ–¹æ–‡æ¡£
    url: https://solitude.js.org/
    img: https://ui.everfu.cn/cover/20240827173743.png/cover
    color: "none"

# æ–‡ç« æ¨èè½®æ’­å›¾
carousel: false

# ä¾§è¾¹æ 
aside:
  home: # on the homepage
    noSticky: "about"
    Sticky: "allInfo"
  post: # on the article page
    noSticky: "about"
    Sticky: "newestPost"
  page: # on the page
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  # èœå•æ ä½ç½®(0: å·¦ 1: å³)
  position: 1 # Sidebar positioning(0: left 1: right)
  # ä¿¡æ¯å¡
  card:
    style: 1 # 0: default 1: style 1 2: style 2
    author:
      img: https://fastly.jsdelivr.net/npm/luoh-blog-static@0.0.7/image/gif/avatar.gif # url
      sticker: # url, 24x24 size
    url: /about/ # link / ç‚¹å‡»å¤´åƒè·³è½¬é“¾æ¥
    background: # https://s3.qjqq.cn/47/663af296b85f4.webp!color # Background image(Invalid if style is 0)
    # å†…å®¹(Style 0 æ— æ•ˆ)
    content: è¿™æ˜¯æˆ‘çš„åšå®¢ / This is my Blog
    content2: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„äºº / A person who loves life
    # Style 2 æ— æ•ˆ
    sayhello:
      morning: âœ¨ æ—©ä¸Šå¥½ï¼Œæ–°çš„ä¸€å¤©å¼€å§‹äº†
      noon: ğŸ² åˆé¤æ—¶é—´
      afternoon: ğŸŒ ä¸‹åˆå¥½
      night: æ—©ç‚¹ä¼‘æ¯
      goodnight: æ™šå®‰ ğŸ˜´
    # Style 2 æ— æ•ˆ, ç‚¹å‡» sayhello æ—¶è§¦å‘
    sayhello2:
      - ä½ å¯ä»¥çš„
      - ä½ ä¸€å®šå¯ä»¥çš„
      - ç¥ä½ å¥½è¿ï¼Œé™Œç”Ÿäºº
    # ç¤¾äº¤ä¿¡æ¯å›¾æ ‡
    information:
     Github: https://github.com/everfu || fab fa-github # Name: link || icon
     Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
  # ä¾§è¾¹æ äºŒç»´ç ç»„ä»¶
  flip:
    favicon: # url (favicon)
    face: # url (QR code)
    backface: # url (QR code)
    backcolor: "var(--efu-blue)" # Background color
  # æ–‡ç« ç›®å½•
  toc:
    post: true
    page: true
    vague: true
  # æ ‡ç­¾
  tags:
    enable: true
    limit: 20 # Number of tags displayed
    highlight_list:
      # - Hexo
  # å½’æ¡£
  archive:
    enable: true
    type: "month" # month: by month / year: by year
  # ç½‘ç«™ä¿¡æ¯
  siteinfo:
    # æ–‡ç« æ•°é‡
    postcount: true
    # æ€»å­—æ•°
    wordcount: true
    # PV
    pv: true
    # UV
    uv: true
    # æœ€åæ›´æ–°æ—¥æœŸ
    updatetime: true
    # ç½‘ç«™åˆ›å»ºæ—¶é—´
    runtimeenable: true
    # æ ¼å¼: yyyy-MM-dd hh-mm-ss
    runtime: "2023-04-20 00:00:00"

# é¡µé¢é»˜è®¤è®¾ç½®
page:
  # 404 é¡µé¢
  error: true
  # æ ‡ç­¾é¡µé¢
  tags: true
  # åˆ†ç±»é¡µé¢
  categories: true
  # list: æ’åºåˆ—è¡¨ / 1: è·Ÿéšé¦–é¡µåˆ—è¡¨
  archives: 0
  # é»˜è®¤å€¼
  default:
    # æœªè®¾ç½®å°é¢æ—¶çš„é»˜è®¤å›¾ç‰‡
    cover:
      - https://api.luoh-an.me/PicLibrary/AnimeImage?t=wallpaper&r=image

# æ–‡ç« é»˜è®¤è®¾ç½®
post:
  default:
    # æ–‡ç« å°é¢æ˜¾ç¤º
    top_cover: true
    # æœªè®¾ç½®å°é¢æ—¶çš„é»˜è®¤å›¾ç‰‡
    cover:
      # -  # é»˜è®¤å›¾ç‰‡ / default cover
    # ä½ç½®
    locate: China
    # ç‰ˆæƒ
    copyright:
      enable: true
      author:
        url: /about/ # Author link
        # é»˜è®¤ä½¿ç”¨ site.icon
        img:
      # è®¸å¯è¯
      license: CC BY-NC-SA 4.0
      # è®¸å¯è¯é“¾æ¥
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  # æ–‡ç« å…ƒä¿¡æ¯
  meta:
    # å‘å¸ƒæ—¥æœŸ
    date: true
    # æ›´æ–°æ—¥æœŸ
    updated: true
    # ä½ç½®
    locate: true
    # å­—æ•°
    wordcount: true
    # uv
    readtime: true
    # pv
    pv: true
    # è¯„è®ºæ•°
    comment: true
  # Reward
  # æ‰“èµ
  award:
    enable: false
    appreciators: /about/ # Reward page
    # æ‰“èµæ ‡é¢˜
    title: # Thanks for your appreciation. / æ„Ÿè°¢æ‚¨çš„èµèµ
    desc: # Because of your support, I realize the value of writing articles. / ç”±äºæ‚¨çš„æ”¯æŒï¼Œæˆ‘æ‰èƒ½å¤Ÿå®ç°å†™ä½œçš„ä»·å€¼ã€‚
    # æ‰“èµåˆ—è¡¨
    list:
      # - name: Github Sponsor
      #   qcode: https://s3.qjqq.cn/47/661ba900c4bc1.webp!color
      #   url: https://github.com/sponsors/everfu
      #   color: var(--efu-black)
  # åˆ†äº«å›¾æ ‡
  share:
    enable: false
    list:
      # - qq
      # - weibo
      # - twitter
      # - facebook
      # - telegram
      # - whatsapp
      # - linkedin
      # - link
      # - qrcode
  rss: # /atom.xml
  # æ–‡ç« å°é¢å–è‰²
  covercolor:
    enable: true
    # local: local color / api: api color / ave: oss average color
    mode: local
    # api åœ°å€
    api: https://api.qjqq.cn/api/Imgcolor?img=
    # ç¼“å­˜æ—¶é—´
    time: 43200000
  footer:
    enable: true
    desc: æ–‡ç« æ¥è‡ª Ever Fu # description
    button: # Button
      enable: true
      name: äº†è§£æ›´å¤š
      url: /about/

# è‡ªå®šä¹‰ä¸»é¢˜é¢œè‰²
theme_color:
  dark: "#ffc848" # dark
  light: "#425AEF" # light

# æ˜¾ç¤ºæ¨¡å¼
display_mode:
  # auto: è‡ªåŠ¨åˆ‡æ¢ï¼ˆè¯†åˆ«è®¾å¤‡å½“å‰ä¸»é¢˜æ¨¡å¼ï¼‰ / dark: æ·±è‰²æ¨¡å¼ / light: æµ…è‰²æ¨¡å¼
  type: auto
  # å¼€å¯åæ·±è‰²æ¨¡å¼ä¼šæ˜¾ç¤ºæ˜Ÿç©ºèƒŒæ™¯
  universe: true

# å­—ä½“
font:
  font-size: 16px
  code-font-size: 16px
  # å…¨å±€å­—ä½“
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  # ä»£ç å­—ä½“
  code-font-family: '"monospace", monospace'

# èƒŒæ™¯å›¾ç‰‡
background:
  enable: false
  opacity: .2
  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg

# é¦–é¡µæ–‡ç« é…ç½®ä¿¡æ¯
index_post_list:
  direction: column # row / column
  column: 2 # 2: 2 columns 3: 3 columns
  cover: both

# ç›¸å…³æ–‡ç« 
related_post:
  enable: true
  limit: 2
  # created: å‘å¸ƒæ—¥æœŸ / updated: æ›´æ–°æ—¥æœŸ
  date_type: updated

# è‡ªå®šä¹‰å³é”®èœå•
right_menu:
  enable: true
  # æ˜¯å¦æ˜¾ç¤ºçƒ­é—¨è¯„è®ºå¼€å…³
  commentBarrage: true
  # æ˜¯å¦åœ¨æŒ‰ä½ Ctrl é”®æ—¶æ˜¾ç¤ºæµè§ˆå™¨å³é”®èœå•
  ctrlOriginalMenu: false
  # ç®€ç¹ä½“è½¬æ¢
  translate: true
  # è‡ªå®šä¹‰åˆ—è¡¨
  custom_list:
    - name: éšæœºæ–‡ç« 
      click: toRandomPost()
      id: menu-randomPost
      class:
      icon: fas fa-tower-broadcast
    - name: å…¨éƒ¨åˆ†ç±»
      click: pjax.loadUrl('/categories/') # External links with window.open, pjax can not request cross-domain content.
      id:
      class:
      icon: fas fa-clone
    - name: å…¨éƒ¨æ ‡ç­¾
      click: pjax.loadUrl('/tags/')
      id:
      class:
      icon: fas fa-tags

# å¤åˆ¶ä¿¡æ¯
copy:
  enable: true
  # å¤åˆ¶åé“¾æ¥ç‰ˆæƒä¿¡æ¯
  copyright:
    enable: true
    # å¤åˆ¶æ–‡å­—æ—¶è¶…è¿‡å¤šå°‘å­—æ•°æ˜¾ç¤º
    limit: 1

mermaid: false
chart: false
typeit: false

# æ§åˆ¶å°
console:
  enable: true
  # æœ€æ–°è¯„è®º
  recentComment:
    enable: true
    # ç¼“å­˜æ—¶é—´ 1: 1å¤© / .5 : åŠå¤©
    storage: .2
  card:
    # æ ‡ç­¾
    tags: true
    # å½’æ¡£
    archive: true

translate:
  enable: true
  defaultEncoding: 2 # 1: é»˜è®¤ç¹ä½“ 2: é»˜è®¤ç®€ä½“
  translateDelay: 0 # é¦–æ¬¡åŠ è½½ç¿»è¯‘è¿Ÿç–‘æ—¶é—´

# å³ä¸‹è§’æ‚¬åœå¯¼èˆªæ 
rightside:
  enable: false
  percent: false
  hide:
    enable: false
    translate: false
    mode: false
    aside: false

# é¡µè„š
footer:
  information:
    author: false # img url / false
    left:
      Github: https://github.com/everfu || fab fa-github # Name: link || icon
      # Mail: mailto:o@everfu.cn || fab fa-envelope
    right:
      Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
      # Douyin: https://v.douyin.com/iJsLc8jt/ || fab fa-tiktok
  group:
    Navigation:
      Archives: /archives/
      Categories: /categories/
      Tags: /tags/
    Arrangement:
      Cookies: /cookies/
      Privacy: /privacy/
      Copyright: /copyright/
  # éšæœºå‹é“¾
  randomlink: false
  # License
  license: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh # License

  # é¡µè„šä¿¡æ¯æ–‡å­—
  links:
    - name: Theme
      url: https://github.com/everfu/hexo-theme-solitude
    # - name: RSS
    #   url: /atom.xml

# 404 é¡µé¢
errorpage:
  img: /img/404.png
  text: =awa= Page Not Found # Text
  recommendList: true

# å¿«æ·èœå•
# ä½¿ç”¨ shift + ? æ‰“å¼€
keyboard:
  enable: false
  list:
    # - name: Close Keyboard
    #   key: K
    #   func: keyboard
    # - name: Open Console
    #   key: A
    #   sco: showConsole
    # - name: Play/Pause Music
    #   key: M
    #   sco: musicToggle
    # - name: Open Links
    #   key: L
    #   url: /links/

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true
  # post, site
  field: site
  # åŠ è½½æ—¶æ›¿æ¢å›¾
  placeholder: /img/loading.gif
  # åŠ è½½å¤±è´¥æ›¿æ¢å›¾
  errorimg: /img/404.png

# åŠ è½½
loading:
  # å…¨å±åŠ è½½
  fullpage: true
  # åŠ è½½å›¾æ ‡ï¼Œä¸å†™é»˜è®¤siteicon
  favicon: https://fastly.jsdelivr.net/npm/luoh-blog-static@0.0.7/image/gif/avatar.gif
  # Pace åŠ è½½
  pace: true

# ä»£ç å—é«˜äº®
highlight:
  enable: true
  # å½“è¶…è¿‡å¤šå°‘å­—æ—¶æ˜¾ç¤ºæŠ˜å æŒ‰é’®
  limit: 200
  # æ˜¯å¦å¯ç”¨å¤åˆ¶æŒ‰é’®
  copy: true
  # æ˜¯å¦é»˜è®¤å±•å¼€
  expand: false
  # default: é»˜è®¤ / mac : è‹¹æœç»ˆç«¯
  theme: mac
  # default / solidity / dracula
  color: default

# å›¾ç‰‡ç¯ç®±
lightbox: true
fancybox: false # fancybox
mediumZoom: true # mediumZoom

# åœ¨çºªå¿µæ—¥æ•´ä¸ªç½‘ç«™å˜ç°
memorial:
  enable: true
  date:
   - 7-7
   - 9-18
   - 12-13 # å›½å®¶å…¬ç¥­æ—¥

# OpenGraph
OpenGraph:
  enable: false
  options:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

# å­—æ•°ç»Ÿè®¡
wordcount: true

# Latex å…¬å¼æ”¯æŒ
katex:
  enable: false
  # æ˜¯å¦åœ¨æ¯ä¸ªé¡µé¢åŠ è½½
  per_page: false
  # æ˜¯å¦å¯ç”¨å¤åˆ¶å…¬å¼
  copytex: false

# CSS å‰ç¼€
# å¼€å¯åä¼šè‡ªåŠ¨ç»™ CSS åŠ å‰ç¼€ï¼ˆä»¥è·å¾—æ›´å¥½çš„æµè§ˆå™¨æ”¯æŒï¼‰ï¼Œä½†è¿™ä¼šå¢åŠ  CSS æ–‡ä»¶çš„å¤§å°ã€‚
css_prefix: true

# æ‰©å±•
extends:
  # æ’å…¥åˆ° head
  head:
  #  - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>

  # æ’å…¥åˆ° body
  body:
  #  - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>

# PWA
pwa:
  enable: true
  manifest: /manifest.json # manifest.json
  theme_color: "#006a73" # Theme color
  mask_icon: /img/pwa/favicon.png # Mask icon
  apple_touch_icon: /img/pwa/favicon.png # Apple touch icon
  bookmark_icon: /img/pwa/favicon.png # Bookmark icon
  favicon_32_32: /img/pwa/32.ico # 32x32 icon
  favicon_16_16: /img/pwa/16.ico # 16x16 icon

# è¯„è®º
comment:
  # ä½¿ç”¨å“ªä¸ªè¯„è®ºç³»ç»Ÿï¼ˆä¾‹å¦‚ï¼š waline or waline,twikooï¼‰
  use: twikoo
  # æ˜¯å¦æ˜¾ç¤ºçƒ­é—¨è¯„è®ºå¼€å…³
  commentBarrage: true
  # æ‡’åŠ è½½è¯„è®ºåŒº
  lazyload: true
  # æ˜¾ç¤ºè¯„è®ºæ•°
  count: true
  # PV
  pv: true
  # Avatar
  avatar: https://gravatar.com/avatar
  # çƒ­è¯„æç¤º
  hot_tip:
    enable: true
    count: 3
  # æœ€æ–°è¯„è®º(âš ï¸ éœ€è¦å…ˆé…ç½®è¯„è®º)
  newest_comment:
    enable: true
    storage: .5 # ç¼“å­˜æ—¶é—´ 1: 1å¤© / .5 : åŠå¤© / Cache time 1: 1 day .5 : half a day
    limit: 5 # è¯„è®ºæ•° / Number of comments

twikoo: # https://twikoo.js.org/
  envId: https://twikoo.luoh-an.me/
  region: # Environment locale, default is ap-shanghai, Tencent cloud environment fill ap-shanghai or ap-guangzhou; Vercel environment do not fill the.
  style: true # Use custom styles when turned on
  accessToken: # AccessToken
  option: # twikoo option

# Search
search:
  enable: true
  type: local # local / algolia
  tags:
    - Solitude
    - Hexo
  local:
    preload: true
    CDN: # url: search.xml

# å¼¹å¹•ç•™è¨€é¡µé¢
envelope:
  enable: true
  line: 10 # æ˜¾ç¤ºè¡Œæ•°
  speed: 20 # æ’­æ”¾é€Ÿåº¦
  hover: true # é¼ æ ‡æ‚¬åœæš‚åœ
  loop: true # å¾ªç¯æ’­æ”¾
  page: /message/ # ç•™è¨€æ¿é¡µé¢

# å³å¯çŸ­æ–‡
says:
  enable: true
  home_mini: true
  page: /essay/
  style: 2
  strip: 9999999999999

# æœ€è¿‘è¯„è®ºé¡µé¢
recent_comments:
  enable: true
  limit: 50 # âš ï¸waline ä»…æ”¯æŒæœ€å¤§50æ¡è¯„è®º
  cache: 0.2 # 1 = 1å¤©
  page: /recentcomments/ # æœ€è¿‘è¯„è®ºé¡µé¢
  img: /img/recent_c.avif # ä¸­æ§å°æ˜¾ç¤ºå›¾ç‰‡ï¼ˆä¸å¡«ä¸æ˜¾ç¤º

# Busuanzi
busuanzi: true
# 0: åŸç‰ˆ / 1: è‡ªå®šä¹‰ç‰ˆ
busuanzi_use: 1

# éå¿…è¦è¯·å‹¿ä¿®æ”¹
CDN:
  internal: custom # local / cdnjs / jsdelivr / unpkg / custom
  third_party: custom # cdnjs / jsdelivr / unpkg / custom
  version: true # Whether to use the version number
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file} # Custom format
  # Directly override the default CDN link (highest priority)
  options:
    # algolia_search:
    # instantsearch:
    # pjax:
    # twikoo:
    # waline_js:
    # waline_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # swiper_css:
    # swiper_js:
    busuanzi_js: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    # snackbar_js:
