site:
  name:
    class: text # text / i_class / img
    custom: è½æ†¾ # Solitude / fas fa-ghost / /img/pwa/favicon.ico
  siteIcon: img/pwa/favicon.png
  icon: img/pwa/favicon.png # Site icon / ç½‘ç«™å›¾æ ‡

# å¯¼èˆªæ 
nav:
  # èœå•
  menu:
     æ–‡ç« :
       åˆ—è¡¨: /archives/ || fas fa-folder-closed
       åˆ†ç±»: /categories/ || fas fa-clone
     æˆ‘çš„:
       éŸ³ä¹é¦†: /music/ || fa-solid fa-music
       ç›¸å†Œ: /album/ || fa-solid fa-images
       # å®è—åšä¸»: javascript:travelling() || fas fa-gift
       # é—²è¨€ç¢è¯­: /essay/ || fa-solid fa-book
       åˆéŸ³æœªæ¥: /mikutap/ || fa-solid fa-guitar
     å…¶ä»–:
       ç©ºè°ƒ: /air-conditioner/ || fa-solid fa-fan
       ç•™è¨€æ¿: /message/ || fa-solid fa-envelope
     å…³äº:
       æœ¬ç«™: /about/ || fas fa-address-card
       éšä¾¿é€›é€›: javascript:toRandomPost() || fa-solid fa-dice

  # å³ä¾§æŒ‰é’®
  right:
    random: false #.éšæœºæ–‡ç« æŒ‰é’®
    custom:
     - name: Start # name
       url: https://www.travellings.cn/go.html # Jump link
       icon: fas fa-train # Icon
       onclick: # Click event
       id: travellings_button # id

# é¦–é¡µé¡¶éƒ¨
hometop:
  enable: true
  banner:
    title: çº¢çº¿è½äººé—´ <br> æ¸…é…’ç ´ä¸‰å¼¦
    url: ä»…æœ›å¾—å›æ¬¢
    icon:
      Java:
        img: https://bu.dusays.com/2023/04/09/643293b1184e9.jpg
        color: "#fff"
      Docker:
        img: https://bu.dusays.com/2023/04/09/643293b0f0abe.png
        color: "#57b6e6"
      Photoshop:
        img: https://bu.dusays.com/2022/12/15/639aa3a5c240e.png
        color: "#4082c3"
      Node:
        img: https://npm.elemecdn.com/anzhiyu-blog@2.1.1/img/svg/node-logo.svg
        color: "#333"
      Webpack:
        img: https://bu.dusays.com/2023/04/09/643293b68026c.png
        color: "#2e3a41"
      Pinia:
        img: https://npm.elemecdn.com/anzhiyu-blog@2.0.8/img/svg/pinia-logo.svg
        color: "#fff"
      Python:
        img: https://bu.dusays.com/2023/04/09/643293b1230f7.png
        color: "#fff"
      Vite:
        img: https://npm.elemecdn.com/anzhiyu-blog@2.0.8/img/svg/vite-logo.svg
        color: "#937df7"
      Flutter:
        img: https://bu.dusays.com/2023/04/09/643293b1055c2.png
        color: "#4499e4"
      Vue:
        img: https://bu.dusays.com/2023/04/09/643293b6788bd.png
        color: "#b8f0ae"
      React:
        img: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ088L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K
        color: "#222"
      CSS3:
        img: https://bu.dusays.com/2022/12/15/639aa3a5c251e.png
        color: "#2c51db"
      JS:
        img: https://bu.dusays.com/2023/04/09/643293b121f02.png
        color: "#f7cb4f"
      HTML:
        img: https://bu.dusays.com/2022/12/15/639aa3a5c241c.png
        color: "#e9572b"
      Git:
        img: https://bu.dusays.com/2023/04/09/643293b10ccdd.webp
        color: "#df5b40"
      Apifox:
        img: https://bu.dusays.com/2022/11/19/6378d6458c6b6.png
        color: "#e65164"
  group:
    çƒ­é—¨: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    sup: Top
    title: èŠ±é—´ä¸€å£¶é…’ï¼Œå‰‘å®¢äºåƒç§‹
    url: https://cdn.cbd.int/luoh-blog@0.0.8/image/webp/banner-image.webp
    img: https://cdn.cbd.int/luoh-blog@0.0.8/image/webp/banner-image.webp
    color: "none"


# æ–‡ç« æ¨èè½®æ’­å›¾
carousel: false

# ä¾§è¾¹æ 
aside:

  # å€¼: about(ä¿¡æ¯å¡), newestPost(æœ€æ–°æ–‡ç« ), allInfo(ç½‘ç«™ä¿¡æ¯), flip(å®˜æ–¹è´¦å·äºŒç»´ç ), newest_comment(æœ€æ–°è¯„è®º)
  # Sticky: å›ºå®šä½ç½® / noSticky: ä¸å›ºå®šä½ç½®
  home: # on the homepage
    noSticky: "about"
    Sticky: "allInfo"
  post: # on the article page
    noSticky: "about"
    Sticky: "newestPost"
  page: # on the page
    noSticky: "about"
    Sticky: "newestPost,allInfo"

  # èœå•æ ä½ç½®(0: å·¦ 1: å³)
  position: 1

  # ä¿¡æ¯å¡
  card:
    style: 1 # 0: default 1: style 1 2: style 2
    author:
      img: https://i1.wp.com/cdn.cbd.int/luoh-blog@0.0.7/image/gif/avatar.gif # url
      sticker: # url, 24x24 size
    url: /about/ # link / ç‚¹å‡»å¤´åƒè·³è½¬é“¾æ¥
    background: https://pic.chino.my.to/i/2024/08/19/565800.webp # Background image(Invalid if style is 0)
    # å†…å®¹(Style 0 æ— æ•ˆ)
    content: è¿™æ˜¯æˆ‘çš„åšå®¢ # è¿™æ˜¯æˆ‘çš„åšå®¢
    content2: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„äºº # ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„äºº
    # Style 2 æ— æ•ˆ
    sayhello:
      morning: æ—©å•Šï¼Œæ–°çš„ä¸€å¤©å¼€å§‹å’¯ â˜€ï¸
      noon: åˆä¼‘æ—¶é—´åˆ°å•¦
      afternoon: ä¸‹åˆèŒ¶ï½ğŸµ
      night: æ—©ç‚¹ç¡å­ ğŸ‚
      goodnight: æ™šå®‰ ğŸ˜´
    # Style 2 æ— æ•ˆ, ç‚¹å‡» sayhello æ—¶è§¦å‘
    sayhello2:
      - æµ·æ°´å€¾è¥¿ä¹±æ»”å¤©
      - å¤§æµªæƒŠèµ·å°½å¯æ€œ
      - è«è¨€ä»¤å·±äº¡èº«é“
      - æƒŸæ„¿è†æ£˜é©»ä¸‡å¹´
    # ç¤¾äº¤ä¿¡æ¯å›¾æ ‡
    information:
      Github: https://github.com/enlt || fab fa-github # Name: link || icon
      Telegram: https://t.me/enltc || fa-brands fa-telegram

  # ä¾§è¾¹æ äºŒç»´ç ç»„ä»¶
  flip:
    favicon: # url (favicon)
    face: # url (QR code)
    backface: # url (QR code)
    backcolor: "var(--efu-blue)" # Background color

  # æœ€æ–°è¯„è®º(âš ï¸ éœ€è¦å…ˆé…ç½®è¯„è®º)
  newest_comment:
    enable: false
    storage: .5 # ç¼“å­˜æ—¶é—´ 1: 1å¤© / .5 : åŠå¤©
    limit: 5 # è¯„è®ºæ•°

  # æ–‡ç« ç›®å½•
  toc:
    post: true
    page: true
    vague: true

  # æ ‡ç­¾
  tags:
    enable: true
    limit: 20 # Number of tags displayed
    # Highlighted tags
    highlight_list:
      - Hexo

  # å½’æ¡£
  archive:
    enable: false
    type: "month" # month/year

  # ç½‘ç«™ä¿¡æ¯
  siteinfo:
    # æ–‡ç« æ•°é‡
    postcount: true
    # æ€»å­—æ•°
    wordcount: true
    # PV
    pv: true
    # UV
    uv: true
    # æœ€åæ›´æ–°æ—¥æœŸ
    updatetime: false
    # ç½‘ç«™åˆ›å»ºæ—¶é—´
    runtimeenable: true
    # æ ¼å¼: yyyy-MM-dd hh-mm-ss
    runtime: "2024-04-23 00:00:00"

# é¦–é¡µæ–‡ç« é…ç½®ä¿¡æ¯
index_post_list:
  direction: column # row / column
  column: 2
  # 1: ä½¿ç”¨è‡ªå·±å†™çš„æ–‡ç« æ‘˜è¦
  # 2: è‡ªåŠ¨è·å–æè¿°æˆ–æˆªå›¾
  # 3: ä»…ä½¿ç”¨æˆªå–
  # false: ä¸æ˜¾ç¤º
  content: true
  # æˆªå›¾å†…å®¹é•¿åº¦
  length: 500
  # left: å·¦ä¾§ : left / right: å³ä¾§ : right / both: ä¸¤ä¾§ : both
  cover: both

# é¡µé¢é»˜è®¤è®¾ç½®
page:
  # 404 é¡µé¢
  error: true
  # æ ‡ç­¾é¡µé¢
  tags: true
  # åˆ†ç±»é¡µé¢
  categories: true
  # list: æ’åºåˆ—è¡¨ / 1: è·Ÿéšé¦–é¡µåˆ—è¡¨
  archives: 0
  # é»˜è®¤å€¼
  default:
    # æœªè®¾ç½®å°é¢æ—¶çš„é»˜è®¤å›¾ç‰‡
    cover:
      - /img/default.png # é»˜è®¤å›¾ç‰‡

# æ–‡ç« é»˜è®¤è®¾ç½®
post:
  default:
    # æ–‡ç« å°é¢æ˜¾ç¤º
    top_cover: true
    # æœªè®¾ç½®å°é¢æ—¶çš„é»˜è®¤å›¾ç‰‡
    cover:
      - img/default.png # é»˜è®¤å›¾ç‰‡ 
    # ä½ç½®
    locate: ä¸­å›½

    # ç‰ˆæƒ
    copyright:
      enable: true
      author:
        url: /about/
        # ä¸å¡«æ˜¾ç¤ºé»˜è®¤å›¾æ ‡
        img: https://i1.wp.com/cdn.cbd.int/luoh-blog@0.0.7/image/gif/avatar.gif
      # è®¸å¯è¯
      license: CC BY-NC-SA 4.0
      # è®¸å¯è¯é“¾æ¥
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh

  # æ–‡ç« å…ƒä¿¡æ¯
  meta:
    # å‘å¸ƒæ—¥æœŸ
    date: true
    # æ›´æ–°æ—¥æœŸ
    updated: false
    # ä½ç½®
    locate: true
    # å­—æ•°
    wordcount: true
    # uv
    readtime: true
    # pv
    pv: true
    # è¯„è®ºæ•°
    comment: true

  # æ‰“èµ
  award:
    enable: false
    appreciators: /about/
    # æ‰“èµæ ‡é¢˜
    title: æ„Ÿè°¢æ‚¨çš„èµèµ
    desc: ç”±äºæ‚¨çš„æ”¯æŒï¼Œæˆ‘æ‰èƒ½å¤Ÿå®ç°å†™ä½œçš„ä»·å€¼ã€‚
    # æ‰“èµåˆ—è¡¨
    list:
      # - name: Github Sponsor
        # qcode: https://s3.qjqq.cn/47/661ba900c4bc1.webp!color
        # url: https://github.com/sponsors/everfu
        # color: var(--efu-black)

  # åˆ†äº«å›¾æ ‡
  share:
    enable: true
    list:
      - qq
      - weibo
      - twitter
      - facebook
      - telegram
      - whatsapp
      - linkedin
      - link
      - qrcode
  rss: # /atom.xml

  # æ–‡ç« å°é¢å–è‰²
  covercolor:
    enable: true
    mode: api
    api: https://api.qjqq.cn/api/Imgcolor?img=
    # Storage / ç¼“å­˜æ—¶é—´
    time: 43200000

  footer:
    enable: false
    desc: æ–‡ç« æ¥è‡ª Ethan Lament
    button: 
      enable: false
      name: Learn more / äº†è§£æ›´å¤š
      url: /about/

# è‡ªå®šä¹‰ä¸»é¢˜é¢œè‰²
theme_color:
  dark: "#a5bda2" # æš—é»‘æ¨¡å¼
  dark_op: "#a5bda2" # æš—é»‘æ¨¡å¼é€æ˜
  dark_op_deep: "#a5bda2" # æš—é»‘æ¨¡å¼é€æ˜æ·±è‰²
  dark_none: "#a5bda2" # æš—é»‘æ¨¡å¼é€æ˜æ— è‰²
  light: "#425AEF" # æ˜äº®æ¨¡å¼
  light_op: "#4259ef23" # æ˜äº®æ¨¡å¼é€æ˜
  light_op_deep: "#4259efdd" # æ˜äº®æ¨¡å¼é€æ˜æ·±è‰²
  light_none: "#4259ef01" # æ˜äº®æ¨¡å¼é€æ˜æ— è‰²

# æ˜¾ç¤ºæ¨¡å¼
display_mode:
  # auto: è‡ªåŠ¨åˆ‡æ¢ï¼ˆè¯†åˆ«è®¾å¤‡å½“å‰ä¸»é¢˜æ¨¡å¼ï¼‰ / dark: æ·±è‰²æ¨¡å¼ / light: æµ…è‰²æ¨¡å¼
  type: auto
  # å¼€å¯åæ·±è‰²æ¨¡å¼ä¼šæ˜¾ç¤ºæ˜Ÿç©ºèƒŒæ™¯
  universe: true

# ç›¸å…³æ–‡ç« 
related_post:
  enable: true
  limit: 2
  # created: å‘å¸ƒæ—¥æœŸ / updated: æ›´æ–°æ—¥æœŸ
  date_type: created

# é¡µè„š
footer:
  information:
    author: false
    left:
       Github: https://github.com/everfu || fab fa-github # Name: link || icon
       Mail: mailto:o@efu.me || fas fa-envelope
    right:
       Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
       Douyin: https://v.douyin.com/iJsLc8jt/ || fab fa-tiktok
  group:
    å¯¼èˆª:
      å½’æ¡£: /archives/
      åˆ†ç±»: /categories/
      æ ‡ç­¾: /tags/
    æœåŠ¡:
      é’æ¡”API: https://api.76.al
      é’æ¡”å›¾åºŠ: https://img.qjqq.cn
    æ”¯æŒ:
      æ‰“èµè®°å½•: /about/
    åè®®:
      Cookies: /cookies/
      éšç§åè®®: /privacy/
      ç‰ˆæƒåè®®: /copyright/

  # éšæœºå‹é“¾
  randomlink: false
  # Privacy policy
  # éšç§æ”¿ç­–
  privacy: /privacy/
  # License
  license: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh # License

  # é¡µè„šä¿¡æ¯æ–‡å­—
  links:
    - name: ä¸»é¢˜
      url: https://github.com/everfu/hexo-theme-solitude
    - name: RSS
      url: /atom.xml

















# 404 é¡µé¢
errorpage:
  img: https://cdn.cbd.int/luoh-blog@0.0.7/image/gif/404.gif
  text: æ€ªå…½æŠŠé¡µé¢æ‹–èµ°äº†...
  recommendList: false

# å³å¯çŸ­æ–‡
says:
  enable: false
  home_mini: false
  page: /essay/
  style: 1
  strip: 30

# æœ€è¿‘è¯„è®ºé¡µé¢
recent_comments:
  enable: false
  limit: 50 # âš ï¸waline ä»…æ”¯æŒæœ€å¤§50æ¡è¯„è®º
  cache: 0.2 # 1 = 1å¤©
  page: /recentcomments/ # æœ€è¿‘è¯„è®ºé¡µé¢
  img: /img/recent_c.avif # ä¸­æ§å°æ˜¾ç¤ºå›¾ç‰‡ï¼ˆä¸å¡«ä¸æ˜¾ç¤ºï¼‰

# å¼¹å¹•ç•™è¨€é¡µé¢
envelope:
  enable: false
  line: 10 # æ˜¾ç¤ºè¡Œæ•°
  speed: 20 # æ’­æ”¾é€Ÿåº¦
  hover: true # é¼ æ ‡æ‚¬åœæš‚åœ
  loop: true # å¾ªç¯æ’­æ”¾
  page: /comment/ # ç•™è¨€æ¿é¡µé¢

copy:
  enable: true
  # å¤åˆ¶åé“¾æ¥ç‰ˆæƒä¿¡æ¯
  copyright:
    enable: false
    # å¤åˆ¶æ–‡å­—æ—¶è¶…è¿‡å¤šå°‘å­—æ•°æ˜¾ç¤º
    limit: 50

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true
  # post, site
  field: site
  # åŠ è½½æ—¶æ›¿æ¢å›¾
  placeholder: /img/loading.gif
  # åŠ è½½å¤±è´¥æ›¿æ¢å›¾
  errorimg: /img/loading.gif
































# ä»£ç å—é«˜äº®
highlight:
  enable: true
  # å½“è¶…è¿‡å¤šå°‘å­—æ—¶æ˜¾ç¤ºæŠ˜å æŒ‰é’®
  limit: 200
  # æ˜¯å¦å¯ç”¨å¤åˆ¶æŒ‰é’®
  copy: true
  # æ˜¯å¦é»˜è®¤å±•å¼€
  expand: true
  # default: é»˜è®¤ / mac : è‹¹æœç»ˆç«¯
  theme: mac
  color: default

# å›¾ç‰‡ç¯ç®±
lightbox: true
# è­¦å‘Š: è¯·ä»»é€‰å…¶ä¸€ï¼Œä½†ä¸èƒ½åŒæ—¶å¼€å¯ã€‚
fancybox: true
mediumZoom: false

wordcount: true

busuanzi: true
busuanzi_use: 1





font:
  font-size: 16px
  code-font-size: 16px
  # å…¨å±€å­—ä½“
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  # ä»£ç å­—ä½“
  code-font-family: '"monospace", monospace'

# è‡ªå®šä¹‰å³é”®èœå•
right_menu:
  enable: true
  # æ˜¯å¦æ˜¾ç¤ºçƒ­é—¨è¯„è®ºå¼€å…³
  commentBarrage: false
  # ç®€ç¹ä½“è½¬æ¢
  translate:
    enable: true
    defaultEncoding: 2 # 1: é»˜è®¤ç¹ä½“ 2: é»˜è®¤ç®€ä½“
    translateDelay: 0 # é¦–æ¬¡åŠ è½½ç¿»è¯‘è¿Ÿç–‘æ—¶é—´
  # è‡ªå®šä¹‰åˆ—è¡¨
  custom_list:
     - name: éšæœºçŸ­æ–‡
       click: toRandomPost()
       id: menu-randomPost
       class:
       icon: fas fa-tower-broadcast
     - name: å…¨éƒ¨åˆ†ç±»
       click: pjax.loadUrl('/categories/')
       id:
       class:
       icon: fas fa-clone
     - name: å…¨éƒ¨æ ‡ç­¾
       click: pjax.loadUrl('/tags/')
       id:
       class:
       icon: fas fa-tags

memorial:
  enable: false
  date:
   - 7-7 # å¢æ²Ÿæ¡¥äº‹å˜
   - 9-18 # ä¹ä¸€å…«äº‹å˜
   - 12-13 # å—äº¬å¤§å± æ€å›½å®¶å…¬ç¥­æ—¥

# èƒŒæ™¯å›¾ç‰‡
background:
  enable: false
  opacity: .2
  dark: https://pic.chino.my.to/i/2024/08/19/565800.webp
  light: https://pic.chino.my.to/i/2024/08/19/565800.webp

# è¯„è®º
comment:
  use: twikoo
  commentBarrage: false # çƒ­è¯„å¼€å…³
  lazyload: true # æ‡’åŠ è½½
  count: true # è¯„è®ºæ•°æ˜¾ç¤º
  avatar: https://cravatar.cn # çƒ­è¯„è·å–å¤´åƒçš„æº
  newest_comment: # æœ€æ–°è¯„è®º
    enable: false
    storage: .2 # ç¼“å­˜æ—¶é—´

# Twikoo é…ç½®ä¿¡æ¯
twikoo: # https://twikoo.js.org/
  envId: https://enltic-twikoo.hf.space/ # ä½ éƒ¨ç½²twikooçš„åœ°å€
  lang: zh-CN # è¯­è¨€
  accessToken: # accessTokenï¼ˆåœ¨æµè§ˆå™¨æ§åˆ¶å°cookiesè·å–ï¼‰

# æœç´¢
search:
  enable: true
  type: local # é€‰æ‹©local
  # æ¨èæ ‡ç­¾
  tags:
  # - Solitude
  # - Hexo
  algolia:
  # hits:
  # per_page: 6
  local:
    preload: true
    CDN:

CDN:
  internal: cbd
  third_party: cdnjs
  version: true
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file} # Custom format
  option:
    busuanzi_qj_js: https://pv.lemonso.com/js
    # algolia_search:
    # instantsearch:
    # pjax:
    twikoo: https://cdn.cbd.int/twikoo@1.6.39/dist/twikoo.all.min.js
    # waline_js:
    # waline_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # swiper_css:
    # swiper_js:
    # busuanzi_js: https://cdn.cbd.int/penndu@1.0.0/bsz.js
    # snackbar_js: